# Generated by Django 6.0.7 on 2026-08-02 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_doctorprofile_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorprofile',
            name='clinic_name',
        ),
    ]
