# Generated by Django 6.0.7 on 2026-08-03 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_appointment_doctor_completed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='patient_showed_up',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('requested', 'Requested'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('absent', 'Patient Absent'), ('disputed', 'Disputed')], default='requested', max_length=20),
        ),
    ]
