# Generated by Django 6.0.7 on 2026-08-05 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_appointment_patient_showed_up_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['requested', 'confirmed'])), fields=('doctor', 'requested_date'), name='unique_active_appointment_slot_per_doctor'),
        ),
    ]
